### ISSUE TITLE
Отказаться от поддержки нескольких контейнеров

### ISSUE THREAD

**Issue by ZFi88** [ReactiveBIM/RxBim#55]
Выпилить поддержку нескольких контейнеров и остаться на `Microsoft.Extensions.DependencyInjection`
Профит:
* Проще подключать RxBim к проектам
* Получаем доступ к `IServiceCollection` в конфигурациях напрямую, а значит можно кофигурить как угодно
* Большинство библиотек поддерживает `Microsoft.Extensions.DependencyInjection` - делают extension методы для `IServiceCollection`

**Comment by ZFi88** [comment]
Могу заняться!

**Comment by zagor-dmtr** [comment]
Хорошая идея!

**Comment by pavlovek** [comment]
> Хорошая идея! Только предлагаю сперва закрыть вот это, а то в конфликтах закопаемся: #48

смержили. можно делать
