### ISSUE TITLE
DI система

### ISSUE THREAD

**Issue by ZFi88** [ReactiveBIM/RxBim#80]
Обратил внимание на изменения актуальной верии `RxBim.DI ` - теперь абстракция `IContainer` дает доступ к `IServiceCollection`. Кажется что в таком случае не нужна абстракция `IContainer`. 

```csharp
/// <summary>
/// DI container abstraction.
/// </summary>
public interface IContainer : IDisposable
{
    /// <summary>
    /// Occurs right after the container is built.
    /// </summary>
    event EventHandler? ContainerBuilt;

    /// <summary>
    /// Services collection.
    /// </summary>
    IServiceCollection Services { get; } // <== ???

    /// <summary>
    /// Services provider.
    /// </summary>
    IServiceProvider ServiceProvider { get; } // <==???
```

Предлагаю избавиться от `IContainer` и использовать конкретный DI контейнер в конфигурациях.

Сделаю pull request с очередной версией `RxBim.DI` - изменения будут ломающие, надо будет подготовиться к переезду.

**Comment by vildar82** [comment]
Федя привет!
Да, изначально так и хотели. Дима делал.  
Но решили оставить наш интерфейс - чтобы все плагины не переделывать.
